import type { User } from "~/types";

const customers: User[] = [
  {
    id: 1,
    name: "Alex Smith",
    email: "alex.smith@example.com",
    phone: "09121234567",
    avatar: {
      src: "https://i.pravatar.cc/128?u=1",
    },
    status: "subscribed",
    role: "admin",
    location: "New York, USA",
  },
  {
    id: 2,
    name: "Jordan Brown",
    email: "jordan.brown@example.com",
    phone: "09121234568",
    avatar: {
      src: "https://i.pravatar.cc/128?u=2",
    },
    status: "unsubscribed",
    role: "advisor",
    location: "London, UK",
  },
  {
    id: 3,
    name: "Taylor Green",
    email: "taylor.green@example.com",
    phone: "09121234569",
    avatar: {
      src: "https://i.pravatar.cc/128?u=3",
    },
    status: "bounced",
    role: "student",
    location: "Paris, France",
  },
  {
    id: 4,
    name: "Morgan White",
    email: "morgan.white@example.com",
    phone: "09121234570",
    avatar: {
      src: "https://i.pravatar.cc/128?u=4",
    },
    status: "subscribed",
    role: "student",
    location: "Berlin, Germany",
  },
  {
    id: 5,
    name: "Casey Gray",
    email: "casey.gray@example.com",
    phone: "09121234571",
    avatar: {
      src: "https://i.pravatar.cc/128?u=5",
    },
    status: "subscribed",
    role: "advisor",
    location: "Tokyo, Japan",
  },
  {
    id: 6,
    name: "Jamie Johnson",
    email: "jamie.johnson@example.com",
    phone: "09121234572",
    avatar: {
      src: "https://i.pravatar.cc/128?u=6",
    },
    status: "subscribed",
    role: "student",
    location: "Sydney, Australia",
  },
  {
    id: 7,
    name: "Riley Davis",
    email: "riley.davis@example.com",
    phone: "09121234573",
    avatar: {
      src: "https://i.pravatar.cc/128?u=7",
    },
    status: "subscribed",
    role: "admin",
    location: "New York, USA",
  },
  {
    id: 8,
    name: "Kelly Wilson",
    email: "kelly.wilson@example.com",
    phone: "09121234574",
    avatar: {
      src: "https://i.pravatar.cc/128?u=8",
    },
    status: "subscribed",
    role: "student",
    location: "London, UK",
  },
  {
    id: 9,
    name: "Drew Moore",
    email: "drew.moore@example.com",
    phone: "09121234575",
    avatar: {
      src: "https://i.pravatar.cc/128?u=9",
    },
    status: "bounced",
    role: "student",
    location: "Paris, France",
  },
  {
    id: 10,
    name: "Jordan Taylor",
    email: "jordan.taylor@example.com",
    phone: "09121234576",
    avatar: {
      src: "https://i.pravatar.cc/128?u=10",
    },
    status: "subscribed",
    role: "advisor",
    location: "Berlin, Germany",
  },
  {
    id: 11,
    name: "Morgan Anderson",
    email: "morgan.anderson@example.com",
    phone: "09121234577",
    avatar: {
      src: "https://i.pravatar.cc/128?u=11",
    },
    status: "subscribed",
    role: "student",
    location: "Tokyo, Japan",
  },
  {
    id: 12,
    name: "Casey Thomas",
    email: "casey.thomas@example.com",
    phone: "09121234578",
    avatar: {
      src: "https://i.pravatar.cc/128?u=12",
    },
    status: "unsubscribed",
    role: "student",
    location: "Sydney, Australia",
  },
  {
    id: 13,
    name: "Jamie Jackson",
    email: "jamie.jackson@example.com",
    phone: "09121234579",
    avatar: {
      src: "https://i.pravatar.cc/128?u=13",
    },
    status: "unsubscribed",
    role: "advisor",
    location: "New York, USA",
  },
  {
    id: 14,
    name: "Riley White",
    email: "riley.white@example.com",
    phone: "09121234580",
    avatar: {
      src: "https://i.pravatar.cc/128?u=14",
    },
    status: "unsubscribed",
    role: "student",
    location: "London, UK",
  },
  {
    id: 15,
    name: "Kelly Harris",
    email: "kelly.harris@example.com",
    phone: "09121234581",
    avatar: {
      src: "https://i.pravatar.cc/128?u=15",
    },
    status: "subscribed",
    role: "admin",
    location: "Paris, France",
  },
  {
    id: 16,
    name: "Drew Martin",
    email: "drew.martin@example.com",
    phone: "09121234582",
    avatar: {
      src: "https://i.pravatar.cc/128?u=16",
    },
    status: "subscribed",
    role: "student",
    location: "Berlin, Germany",
  },
  {
    id: 17,
    name: "Alex Thompson",
    email: "alex.thompson@example.com",
    phone: "09121234583",
    avatar: {
      src: "https://i.pravatar.cc/128?u=17",
    },
    status: "unsubscribed",
    role: "student",
    location: "Tokyo, Japan",
  },
  {
    id: 18,
    name: "Jordan Garcia",
    email: "jordan.garcia@example.com",
    phone: "09121234584",
    avatar: {
      src: "https://i.pravatar.cc/128?u=18",
    },
    status: "subscribed",
    role: "advisor",
    location: "Sydney, Australia",
  },
  {
    id: 19,
    name: "Taylor Rodriguez",
    email: "taylor.rodriguez@example.com",
    phone: "09121234585",
    avatar: {
      src: "https://i.pravatar.cc/128?u=19",
    },
    status: "bounced",
    role: "student",
    location: "New York, USA",
  },
  {
    id: 20,
    name: "Morgan Lopez",
    email: "morgan.lopez@example.com",
    phone: "09121234586",
    avatar: {
      src: "https://i.pravatar.cc/128?u=20",
    },
    status: "subscribed",
    role: "student",
    location: "London, UK",
  },
];

export default eventHandler(async () => {
  return customers;
});
